import { MaterialConfig } from '../types/cad';

export const DEFAULT_MATERIALS: MaterialConfig[] = [
  {
    id: 'mat_mdflam_white',
    name: 'MDFLAM Mat Beyaz',
    type: 'mdflam',
    color: '#f1f5f9',
    texturePattern: 'solid',
    grainDirection: 'none',
    roughness: 0.35,
    metalness: 0.05,
    sheetWidth: 2800,
    sheetHeight: 2100,
    defaultThickness: 18,
    unitPricePerM2: 380, // TL/m2
    edgeBandPricePerM: 12, // TL/m
    cuttingPricePerM: 10,
  },
  {
    id: 'mat_mdflam_oak',
    name: 'MDFLAM Doğal Meşe',
    type: 'mdflam',
    color: '#d4a373',
    texturePattern: 'wood-grain',
    grainDirection: 'length',
    roughness: 0.6,
    metalness: 0.05,
    sheetWidth: 2800,
    sheetHeight: 2100,
    defaultThickness: 18,
    unitPricePerM2: 460,
    edgeBandPricePerM: 16,
    cuttingPricePerM: 10,
  },
  {
    id: 'mat_mdflam_walnut',
    name: 'MDFLAM Sıcak Ceviz',
    type: 'mdflam',
    color: '#8b5a2b',
    texturePattern: 'wood-grain',
    grainDirection: 'length',
    roughness: 0.55,
    metalness: 0.05,
    sheetWidth: 2800,
    sheetHeight: 2100,
    defaultThickness: 18,
    unitPricePerM2: 490,
    edgeBandPricePerM: 18,
    cuttingPricePerM: 10,
  },
  {
    id: 'mat_mdflam_anthracite',
    name: 'MDFLAM Antrasit Gri',
    type: 'mdflam',
    color: '#334155',
    texturePattern: 'solid',
    grainDirection: 'none',
    roughness: 0.4,
    metalness: 0.1,
    sheetWidth: 2800,
    sheetHeight: 2100,
    defaultThickness: 18,
    unitPricePerM2: 420,
    edgeBandPricePerM: 15,
    cuttingPricePerM: 10,
  },
  {
    id: 'mat_suntalam_light',
    name: 'Suntalam Açık Huş',
    type: 'suntalam',
    color: '#e2d4c0',
    texturePattern: 'wood-grain',
    grainDirection: 'length',
    roughness: 0.65,
    metalness: 0.02,
    sheetWidth: 2800,
    sheetHeight: 2100,
    defaultThickness: 18,
    unitPricePerM2: 290,
    edgeBandPricePerM: 10,
    cuttingPricePerM: 8,
  },
  {
    id: 'mat_lake_gloss_white',
    name: 'Lake Parlak Beyaz',
    type: 'lake',
    color: '#ffffff',
    texturePattern: 'solid',
    grainDirection: 'none',
    roughness: 0.1,
    metalness: 0.2,
    sheetWidth: 2800,
    sheetHeight: 2100,
    defaultThickness: 18,
    unitPricePerM2: 850,
    edgeBandPricePerM: 25,
    cuttingPricePerM: 15,
  },
  {
    id: 'mat_masif_pine',
    name: 'Masif Doğal Çam',
    type: 'masif',
    color: '#c89d66',
    texturePattern: 'wood-grain',
    grainDirection: 'length',
    roughness: 0.7,
    metalness: 0.0,
    sheetWidth: 2400,
    sheetHeight: 1200,
    defaultThickness: 22,
    unitPricePerM2: 950,
    edgeBandPricePerM: 20,
    cuttingPricePerM: 18,
  },
  {
    id: 'mat_kontrplak',
    name: 'Kontrplak Huş (Plywood)',
    type: 'kontrplak',
    color: '#e6ccb2',
    texturePattern: 'wood-grain',
    grainDirection: 'length',
    roughness: 0.5,
    metalness: 0.0,
    sheetWidth: 2500,
    sheetHeight: 1250,
    defaultThickness: 18,
    unitPricePerM2: 650,
    edgeBandPricePerM: 15,
    cuttingPricePerM: 12,
  },
  {
    id: 'mat_back_panel_8mm',
    name: 'Arkalık MDFLAM 8mm',
    type: 'mdflam',
    color: '#f8fafc',
    texturePattern: 'solid',
    grainDirection: 'none',
    roughness: 0.4,
    metalness: 0.05,
    sheetWidth: 2800,
    sheetHeight: 2100,
    defaultThickness: 8,
    unitPricePerM2: 190,
    edgeBandPricePerM: 0,
    cuttingPricePerM: 6,
  },
  {
    id: 'mat_glass_smoked',
    name: 'Füme Temperli Cam',
    type: 'glass',
    color: '#475569',
    texturePattern: 'glass',
    grainDirection: 'none',
    roughness: 0.05,
    metalness: 0.9,
    sheetWidth: 2000,
    sheetHeight: 1000,
    defaultThickness: 4,
    unitPricePerM2: 700,
    edgeBandPricePerM: 0,
    cuttingPricePerM: 20,
  },
  {
    id: 'mat_metal_black',
    name: 'Mat Siyah Metal/Profil',
    type: 'metal',
    color: '#1e293b',
    texturePattern: 'metal',
    grainDirection: 'none',
    roughness: 0.3,
    metalness: 0.8,
    sheetWidth: 3000,
    sheetHeight: 100,
    defaultThickness: 2,
    unitPricePerM2: 450,
    edgeBandPricePerM: 0,
    cuttingPricePerM: 15,
  }
];

export const HARDWARE_PRICES = {
  hingeSoftClose: 45, // TL / piece (Frenli Menteşe)
  drawerSlideTelescopic: 120, // TL / pair (Teleskopik Ray)
  drawerSlideUndermount: 280, // TL / pair (Frenli Gizli Ray)
  handleModernBar: 65, // TL / piece (Modern Kulp)
  handleKnob: 35, // TL / piece (Düğme Kulp)
  minifixSet: 8, // TL / set (Minifix + Kavela)
  adjustableLeg: 25, // TL / piece (Ayarlanabilir Baza Ayağı)
  shelfPin: 3, // TL / piece (Raf Pimi)
};
